---
name: Build Golem Editions

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-kiosk:
    runs-on: ubuntu-latest
    name: Build Zero-Config (Kiosk)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Kiosk)
        uses: docker/build-push-action@v5
        with:
          context: .
          target: kiosk
          push: true
          # dynamically uses the username secret
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/golem-kiosk:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-desktop:
    runs-on: ubuntu-latest
    name: Build Power-User (Desktop)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Desktop)
        uses: docker/build-push-action@v5
        with:
          context: .
          target: desktop
          push: true
          # dynamically uses the username secret
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/golem-desktop:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
